name: Lint & type-check

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  lint:
    name: Lint & type-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-linux-deps

      - uses: ./.github/actions/setup-build

      - name: TypeScript
        run: pnpm typecheck
